### ISSUE TITLE
Is it supposed to support tagnames such as xx:name?

### ISSUE THREAD

**Issue by aterreno** [goto100/xpath#11]
Hi, I am trying to use xpath to parse a soap message, the tags are all prefixed, I've changed your example to this test, by adding the hc: in front of the title tag: 

```javascript
var xpath = require('xpath');
var dom = require('xmldom').DOMParser;

describe('XPATH', function () {
  describe('#select()', function () {
    it('should work', function (done) {
      var doc = new dom().parseFromString("<book><hc:title>Harry Potter</hc:title></book>");
      var nodes = xpath.select("//hc:title", doc)
      // console.dir(nodes);
      done();
    });
  })
});
```

I'll probably try to digg into the code and figure out where is the issue, I haven't done xpath in years but I assume that having a path with a semicolon should be valid.

**Comment by JLRishe** [comment]
The unit tests in this repo also provide two examples of using namespaces. (BTW your example XML is invalid because the `hc` prefix isn't declared, but I imagine the XML you're actually trying to work with properly declares its namespaces.

**Comment by keithdtyler** [comment]
var xml = "<book xmlns:bookml='http://example.com/book'><bookml:title>Harry Potter</bookml:title></book>"
    var select = xpath.useNamespaces({"bookml": "http://example.com/book"});

Seriously? We need to tell xpath to do something that is specifically indicated IN the xml? If I have to rewrite the contents of the XML in order for xpath to read it what is the point of parsing the xml in the first place? This is a freaking nightmare in any content with multiple namespaces. I have to track down all the xmlns in the XML and then explicitly tell xpath to use them? That's great if you're hand-crafting XML, not so great if your XML comes from somewhere else.

**Comment by JLRishe** [comment]
@keithdtyler This is true of almost any decent XPath API and it's not a "freaking nightmare". See how it's done in [C#](http://stackoverflow.com/questions/14370989/how-do-i-select-nodes-that-use-a-default-namespace), [Java](http://stackoverflow.com/questions/23203421/javax-xml-xpath-is-not-extracted-from-xml-with-namespaces), and [Python](http://stackoverflow.com/questions/14853243/parsing-xml-with-namespace-in-python-via-elementtree).

Otherwise, how would you propose the library should work if you had this (perfectly valid) XML with the same prefix referring to two different namespaces?:

````
<my:book xmlns:my="http://example.com/book">
    <my:chapter xmlns:my="http://example.com/chapter">The Boy Who Lived</my:chapter>
<my:chapter>
````

>  If I have to rewrite the contents of the XML in order for xpath to read it what is the point of parsing the xml in the first place?

You shouldn't be rewriting the contents of the XML. You just need to provide a plain object listing the namespaces your XPath needs.

> I have to track down all the xmlns in the XML and then explicitly tell xpath to use them? 

Typically you should know ahead of time what format the XML you're consuming has and what namespaces it is using. If you are working with arbitrary XML and XPaths, then yes, you would need to walk the XML to find its namespaces.

Bear in mind that your namespace list does not have to use the same prefixes as the XML as long as the URIs match.

````
var xml = "<book xmlns:bookml='http://example.com/book'><bookml:title>Harry Potter</bookml:title></book>";
var doc = new dom().parseFromString(xml);
var select = xpath.useNamespaces({"theTotallyCoolBookNamespace": "http://example.com/book"});
console.log(select('/book/theTotallyCoolBookNamespace:title', doc)[0].textContent);
