### ISSUE TITLE
No matches when searching by tagName in XMLDOM's text/html DOM

### ISSUE THREAD

**Issue by moll** [goto100/xpath#27]
Hey,

Giving Xpath a spin with XMLDOM. I can't seem to get it to match any elements by tag name when the DOM's MIME type is set to `text/html`. Is it supposed to work?

``` javascript
var Xpath = require("xpath")
var DomParser = require("xmldom").DOMParser

var html = "<html><head><title>Harry Potter</title></head></html>"
var doc = new DomParser().parseFromString(html, "text/html")
console.log(Xpath.select("//title", doc))
```

The above returns an empty array. Add a random attribute to an element, try to match by that instead  (`//*[@foo=123]`) and it works.

Thanks!

**Comment by moll** [comment]
I've tracked this down to the difference between `namespaceURI`. DOM elements all have it set to `http://www.w3.org/1999/xhtml`, but the Xpath query doesn't. Xpath also doesn't apply the default namespace to query tag names.

Would you mind changing Xpath so it would? Prefixing every tag in the query with the XHTML namespace is rather cumbersome. Thanks!

**Comment by JLRishe** [comment]
@moll What is it exactly that you are suggesting be changed? If the nodes have a namespace, then they must be accessed with a namespace prefix:

http://www.w3.org/TR/xpath/#node-tests

> A QName in the node test is expanded into an expanded-name using the namespace declarations from the expression context. ***This is the same way expansion is done for element type names in start and end-tags except that the default namespace declared with xmlns is not used: if the QName does not have a prefix, then the namespace URI is null (this is the same way attribute names are expanded).

**Comment by moll** [comment]
Perhaps a way to set a default namespace for unqualified names. The `useNamespaces` feature is already there. It's just not available for queries.

Try the example above. It's rather cumbersome to prefix _every_ tag name with either the full namespace URI or an alias -> `//div/h3/span` turns into `//html:div/html:h3/html:span` in the best case.

**Comment by JLRishe** [comment]
As someone who uses XPath a lot, I don't see it as all that cumbersome to use prefixes most of the time, but you definitely have a valid point in that the original library had a `useNamespaces` option.

(Incidentally, the best case is `//h:div/h:h3/h:span`; you should not be limited to using any particular prefix)

I don't currently have collaborator access to this repo and the owner doesn't seem to be checking pull requests. I have actually just sent an e-mail to the owner asking whether they could make me a collaborator. If that happens, I would be willing to expose the `useNamespaces` option via the external wrapper.

**Comment by moll** [comment]
The`useNamespaces` is already available here, too. It's just that its support for the default namespace isn't enabled for query names. I created a wrapper with a regexp replace to auto-prefix names, but it's all rather silly when all you've got are nodes in the (x)HTML namespace.

**Comment by JLRishe** [comment]
I see, I confused myself. The XPath evaluator has a "case insensitive mode" (which was never exposed externally), and I had misremembered this as an "ignore namespaces mode".

I would not be in favor of outright supporting non-null default namespaces, because as silly as it may seem, that would violate the XPath 1.0 spec. Most professional XPath implementations (.NET, most XSLT engines, etc.) do not allow using a default namespace because the spec is quite clear on the point that XPath 1.0 has no such capacity.

**Comment by moll** [comment]
What's the default namespace feature for then? Querying HTML DOMs with Xpath here is simply too cumbersome out of the box. Why not make it more convenient is what I'm proposing. That's what computers are for — to handle repetitive tasks for us. ;-)

**Comment by JLRishe** [comment]
> What's the default namespace feature for then?

Which feature are you referring to? I see that the `Utilities.resolveQName` method has a `useDefault` parameter, but it is always passed in as `false`.

> Querying HTML DOMs with Xpath here is simply too cumbersome out of the box.

I don't see what's so cumbersome about adding an extra two characters to each step of an XPath. People who work with XML do this all the time.

> Why not make it more convenient is what I'm proposing.

Because, as I already said, it would violate the XPath 1.0 spec. I think spec compliance is a worthwhile thing, especially with a library like this. It could also certainly have unintended consequences for someone using the library and expecting it to behave according to the spec.

> That's what computers are for — to handle repetitive tasks for us.

Yes, but not at the expense of spec compliance.

**Comment by Blahah** [comment]
> I don't really see what's so terribly cumbersome about adding an extra two characters to each step of an XPath. People who work with XML do this all the time.

It's only practical to add namespaces to queries when working with tightly controlled corpora. An example scenario is when you have a set of XPath selectors that you want to apply to a large set of HTML documents. Those documents may or may not be explicitly namespaced, and namespaces may differ between documents (HTML4/xhtml etc.). In this case it's not possible to add namespaces to queries so that they apply to the whole corpus, but by using default namespaces you can resolve the problem with minimal hacking.

**Comment by indianscout** [comment]
Same issue here. I agree with @moss. The following sould work, but it does not:
```
> var xmldom = require('xmldom');
> var xpath = require('xpath')
> var parser = new xmldom.DOMParser();
> var doc = parser.parseFromString('<html lang=\"en\"><head><meta charset=\"utf-8\" /></head><body></body></html>', 'text/html');
> xpath.select('//body', doc);
[]
> var doc = parser.parseFromString('<html lang=\"en\"><head><meta charset=\"utf-8\" /></head><body></body></html>', 'text/xml');
> xpath.select('//body', doc);
[ Element {
    _nsMap: {},
    attributes: { _ownerElement: [Circular] },
    childNodes: {},
    ownerDocument: 
     Document {
...
> 
```
In my opinion xpath should return the body element also on documents with text/html... text/html is a valid mime type (https://developer.mozilla.org/en/docs/Web/API/DOMParser).

Or is there any good reason for xpath to refuse to operate on text/html?

**Comment by JLRishe** [comment]
@indianscout 
> Or is there any good reason for xpath to refuse to operate on text/html?

This library operates on text/html just fine. It is simply strict with regards to namespaces, and html elements are in the `http://www.w3.org/1999/xhtml` namespace.

The following works:

```
var xmldom = require('xmldom');
var xpath = require('xpath')

var parser = new xmldom.DOMParser();
var doc = parser.parseFromString(
              '<html lang=\"en\"><head><meta charset=\"utf-8\" /></head><body></body></html>', 
              'text/html');

var select = xpath.useNamespaces({ h: 'http://www.w3.org/1999/xhtml' });
var body = select('//h:body', doc);
console.log(body);
```

**Comment by JLRishe** [comment]
I'm going to keep this open a little longer for a few more potential changes.

**Comment by sdeprez** [comment]
👋  hi, just to add some content to that because it also got me confused (and initially I thought it was a bug of `xmldom` and I opened https://github.com/xmldom/xmldom/issues/377). To summarize the issue:
1. when you parse doc with type `text/html`, `xmldom` (but also the browser) adds a default namespace `http://www.w3.org/1999/xhtml`
2. when you query that doc, a simple xpath `//input` won't work because of namespace

IIUC, 2. won't work because this library is strict with xpath 1.0 specs (which makes sense), so we need to provide the namespace. The reason it's working in browsers, is that browsers follow the  the `html` spec, which adds [a modification](https://html.spec.whatwg.org/#interactions-with-xpath-and-xslt) ("willful violation" as they say) to this spec to specifically handle that case.

I'm not sure how feasible is it to add a boolean param / mode to also support here that modified spec, but at the least, it'd be nice to document that behaviour, because it's very easy to fall into that trap, and it's easy to get lost because browsers work differently. I can work on a PR if you agree on the analysis.

**Comment by JLRishe** [comment]
@sdeprez I can't find any place where this is documented or mentioned explicitly, but cae87df9916c6449282d5c10a88bf5e90d76f7e1 added an `isHtml` option which allows you to use this library in "HTML Mode" and not have to explicitly declare the html namespace. It requires using parsed expressions.

```js
const path = xpath.parse('//input');
const nodes = path.select({ node: myHtmlDom, isHtml: true });
```

You can see some examples of this in this repo's test.js file.

**Comment by sdeprez** [comment]
Thanks! It looks like `isHtml ` is indeed what I need. 

On the other hand, I needed to use `.evaluate` and it took me some time to understand the usage of `require('xpath').evaluate(...` vs `xpath.parse('//input').evaluate(...` since they behave differently, I also noticed that typescript typings are not mentioning `.evaluate` methods. Would it be possible to add:
- a note about this html quirk and `isHtml` on the main readme
- add `.evaluate` in [api docs](https://github.com/goto100/xpath/blob/master/docs/xpath%20methods.md) and in [typescript typings](https://github.com/goto100/xpath/blob/master/xpath.d.ts)

I can work on a PR if you agree on the principle

**Comment by JLRishe** [comment]
@sdeprez Sorry for not getting back to you sooner.

We actually have an [API page](https://github.com/goto100/xpath/blob/master/docs/XPathEvaluator.md) that mentions the .evaluate() method, but it takes a bit of digging to get there:

[api docs](https://github.com/goto100/xpath/blob/master/docs/xpath%20methods.md) -> link under xpath.parse ->  "documentation page" link

Maybe it would be better to have `XPathEvaluator` on the Parsed Expressions page to link to the API doc for XPath Evaluator, and provide a bit more explanatory text and examples on the Parsed Expressions page.

The XPathEvaluator page also doesn't include information about the `isHtml` option.

I'd be happy to look at a PR if you can submit one. Thanks!
