### ISSUE TITLE
Handle XML CDATA

### ISSUE THREAD

**Issue by bluepuma77** [goto100/xpath#30]
As CDATA is part of the XML specification, I think xpath should abstract the handling of it.

```
var xpath = require('xpath');
var dom = require('xmldom').DOMParser;
var xml = "<MediaFile><![CDATA[https://server]]></MediaFile>";
var doc = new dom().parseFromString(xml);
var file = xpath.select("//MediaFile/text()", doc).toString();
console.log(file);
```

In my opinion xpath should return "```https://server```", not "```<![CDATA[https://server]]>```".

**Comment by JLRishe** [comment]
When you call `xpath.select()` on an expression that evaluates to a nodeset (and that is the case here), it returns an array of DOM nodes.

What you are doing here is calling `.toString()` on an array, which is producing a concatenation of the `.toString()` values of its elements.

So this isn't really an issue with the xpath library's treatment of CDATA sections. The library handles their string values correctly, but you are effectively using `.toString()` directly on DOM nodes and that depends on their default behavior.

To get around this:

Option 1: Wrap your expression in a `string()` function, so that `.select()` produces a string:

    var file = xpath.select("string(//MediaFile/text())", doc);
    console.log(file);

Option 2: Use the parsed expression functionality that I have added in [my fork of this project](https://github.com/JLRishe/xpath). This provides methods to allow selecting the result type that you want:

    var file = xpath.parse("//MediaFile/text()").evaluateString({ node: doc });
