### ISSUE TITLE
Definitions of select() and select1() in xpath.d.ts are incorrect

### ISSUE THREAD

**Issue by jacks50** [goto100/xpath#70]
@JLRishe : I opened an issue as requested. Please let me know if you need any additional information.

After updating the modules I am using in my project, some errors appeared in the mentionned functions.

From what the API documentation states (and also what I have done in my project), it says : 
- `xpath.select(query, context, isSingle)` where context is a `Node` (optional) and `isSingle` specifies if the result evaluates to a `nodeset` or not
- `xpath.select1(query, context)` which is basically calling `xpath.select(query, context, true)`

But after update, when calling the mentionned functions, this is what Visual Studio (in my case) shows me :
- it tells me that `select()` is a variable and not a function
- it shows me two overloads for `select()` 
=> `select(expr: string, node: Node, single: true): xpath.SelectedValue`
=> `select(expr: string [, node: Node]): xpath.SelectedValue[]`
- it tells me that `select1()` is indeed a function and its signature is `select1(expr: string [, node: Node])`
- it showed errors about using `xpath.select( ... ).value` for attributes (should I be using `valueOf` ??)

Some explanations are welcomed since the way attributes have changed, and also the returned values of functions seem to be of another type. Nothing is mentionned in the documentation. Did I do something weird ?

Using xpath v0.0.24 and NodeJS v7.0.12

**Comment by JLRishe** [comment]
It looks like you're seeing errors in VS because if the addition of the xpath.d.ts definition file. The `select()` and `select1()` methods themselves have not changed in a long time and they should work as described. 

I will work on correcting the inaccuracies in the .d.ts file when I can, but for now, you should be able to get rid of those errors by deleting the .d.ts file.

**Comment by Jacks50** [comment]
If I delete the .d.ts file, I won't be able to use your module in TypeScript right ?

**Comment by JLRishe** [comment]
Were you using this library prior to version 0.0.24? If so, then you should have no problem without the .d.ts file.

I haven't used TypeScript much, but I believe you would either need to cast the return values using <any> or a concrete type <Attr>. I don't believe the absence of a .d.ts file should completely prevent you from using the library in TypeScript.

Of course, if you'd like to improve the .d.ts file and make a pull request, I would be happy to review it.

**Comment by Jacks50** [comment]
Yes, I was using it prior to version 0.0.24, but using modules in TypeScript requires a `definition file` which basically describes the module in .js format. If I delete it, TypeScript does not recognizes the import of `xpath`, stating that `xpath.d.ts` is not a module (because it didn't find it I guess). I'm not an expert on TypeScript : In fact I learned it some months ago so it's kinda fresh.

I've seen in the .d.ts file that the `SelectedValue` type can be a `boolean`, a `number`, a `Node`, etc .. So I'll go with type casting. When I was first using your library, my function was supposed to return a `Node`, but since `SelectedValue` is a mix of types (in the .d.ts file), it generated errors.

I am sorry, I am not able to create a clean-and-optimal .d.ts file because of my lack of knowledge unfortunately .. It is a bit hard to understand how to make it the right way :(

Feel free to ask me anything if you need some explanation and / or help, I will do what I can. Thank you for your time !

**Comment by JLRishe** [comment]
How were you using it prior to version 0.0.24? There was no .d.ts file until version 0.0.24.

**Comment by Jacks50** [comment]
Ah now I remember it .. You are right, there was no .d.ts file so I had to get one from **DefinitelyTyped**. That is why this file has "changed" in my case : in fact, you added your own, and then everything went wrong on my side. I totally forgot about this special case in my project.

Anyway, I've pasted the code of the .d.ts file [here](http://paste.ubuntu.com/24414065/), maybe it can be of some help ? This is the version I used, but yours seems okay, I managed to type cast and it looks correct (not tested yet though).

**Comment by JLRishe** [comment]
The new .d.ts file here isn't actually mine. Somebody else made a pull request for it and I merged it because I didn't see any obvious issues, but it looks like it is a bit inaccurate. I will try to improve it within the next week or so.

**Comment by Jacks50** [comment]
Thank you very much @JLRishe for your time ! I will let you close the issue once resolved, tell me if I can be of any help

**Comment by JLRishe** [comment]
I know this is extremely late, but some work was done on this earlier in the year and this should hopefully be ok now. Thank you for initially raising this issue.
