### ISSUE TITLE
Make allowAnyNamespaceForNoPrefix=true the default

### ISSUE THREAD

**Issue by dwaputin** [goto100/xpath#77]
When trying to query kml-datasets generated by different geolocation apps -> empty nodesets are returned, if default namespace is given in the root-node, like:
`<kml xmlns="http://www.opengis.net/kml/2.2" ...>`

Some _strictMode_-parameter  (not defined by default) might be added to the arguments of select-cmds? 
The attached dataset is processed correctly if  `setIfUnset(c, 'allowAnyNamespaceForNoPrefix', true);
` is placed in main function-body of `XPath.prototype.evaluate` in every case.
 
[track.zip](https://github.com/goto100/xpath/files/1625516/track.zip)

**Comment by JLRishe** [comment]
The `allowAnyNamespaceForNoPrefix` option was added as a concession for issue #27 because, by convention, querying HTML without prefixes is typically allowed even though HTML nodes are typically in a namespacce.

I am not going to make that option on by default. This library is first and foremost an XPath 1.0-compliant library which means it respects namespaces. Frankly, if you're working with XML, you should be using namespaces properly and not circumventing them by using this option.

**Comment by OnkelTem** [comment]
allowAnyNamespaceForNoPrefix - where should I set this option? I didn't find it anywhere in the docs.
