### ISSUE TITLE
How to get innerHTML of the element?

### ISSUE THREAD

**Issue by ProgrammingLife** [goto100/xpath#93]
Is there a way to get HTML code of some selected node?

**Comment by JLRishe** [comment]
If you are working with an HTML DOM, then the nodes returned by the XPath queries are just HTML nodes, so you should be able to access their .innerHTML properties.

**Comment by JLRishe** [comment]
Feel free to add another comment if you still can't figure it out, but please share the relevant code next time.

**Comment by diegodlh** [comment]
Hi! I think I'm having the same problem. I have an HTML string like this:

```
const sampleHtml = "\
<!DOCTYPE html>\
<html>\
  <head></head>\
  <body>\
    <book author='Virginia Woolf'>\
    <title>Orlando</title>\
  </book>\
  <book author='James Gleick'>\
    <title>The Information</title>\
  </book>\
  </body>\
</html>\
  "
```
I parse it with xmldom v0.8.0 like this: `const dom = new DOMParser().parseFromString(sampleHtml, 'text/html')`.

Then, I pre-parse an XPath expression with this library's v0.0.32: `const parsedXPath = xpath.parse('//book[@author='Virginia Woolf']')`.

Finally, I evaluate the parsed expression on the dom created above, and convert the result into an array of nodes: `parsedXPath.evaluate({node: dom, isHtml: true}).nodeset().toArray()`.

However, the nodes returned are instances of `Node` instead of instances of `HTMLElement`, and thus have not `innerHTML` or `innerText` methods; just `textContent`.

**Comment by JLRishe** [comment]
@diegodlh The DOM standard property for accessing a node's text content is [`.textContent`](https://dom.spec.whatwg.org/#dom-node-textcontent). `.innerText` is not part of the DOM standard.

I believe `.textContent` will provide what you need. Can you please give that a try?

**Comment by diegodlh** [comment]
Unfortunately, `innerText` and `textContent` do not return the same thing. See [here](https://developer.mozilla.org/en-US/docs/Web/API/Node/textContent#differences_from_innertext).

I ended up using `textContent` and running `.replace(/[\t\n\r ]+/g, " ")` on it as a workaround.

**Comment by JLRishe** [comment]
@diegodlh You're having to remove a bunch of whitespace because you're selecting a `<book>` element and getting its `.textContent`, and it has several text nodes within it:

- A text node before `<title>`, which contains a newline and some spaces (and maybe tabs)
- A text node within `<title>`, which contains the title
- A text node after `<title>` which is similar to the one before `<title>` (a bunch of whitespace)

`.textContent` returns a concatenation of _all_ text content within the current node.

If what you want is the title, then you should select the `<title>` element:

```js
const parsedXPath = xpath.parse('//book[@author = "Virginia Woolf"]/title')
```

That way you don't need to strip out the whitespace.

One more piece of advice: I'm guessing that in practice the `"Virginia Woolf"` part of your XPath is going to vary, but concatenating a string literal into an XPath is risky since the presence of quote characters could break the XPath.

Instead, you should use a variable within the XPath:

```js
const parsedXPath = xpath.parse('//book[@author = $author]/title');
const nodes = parsedXPath.select({     // or use .evaluateString instead of .select
    node: dom,
    isHtml: true,
    variables: { author: 'Virginia Woolf' },
});
```
